//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILE_CONTENT
    {
        public int ID { get; set; }
        public int FILE_ID { get; set; }
        public string CONTENT { get; set; }
    }
}
